import "../styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Navbar from "../components/header";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>blackant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/Logo.svg" />
      </Head>
      <header className="fixed w-full z-50">
        <Navbar black={false} />
      </header>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
