import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import Navbar from "../components/header";
import Section1 from "../components/sections/section1";
import Section2 from "../components/sections/section2";
import Section3 from "../components/sections/section3";
import Section4 from "../components/sections/section4";
import Section5 from "../components/sections/section5";
import { motion, AnimatePresence, useScroll } from "framer-motion";
import {
  anim_x,
  anim_x0y1,
  anim_x1y0,
  anim_y,
  containerSpringTransition,
  hidden_left,
  screenSpringTransition,
} from "../utils/animation_variants";

const Home: NextPage = () => {
  const [sections, setSections] = useState({
    sec1: true,
    sec2: false,
    sec2exit: false,
    sec3: false,
    sec4: false,
    sec4exit: false,
    sec5: false,
    navBlack: false,
  });

  return (
    <>
      <Head>
        <title>blackant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/Logo.svg" />
      </Head>

      <header className="fixed w-full z-50">
        <Navbar black={sections.navBlack} />
      </header>

      <main className="relative w-screen h-screen overflow-hidden">
        <motion.div
          key={"section1"}
          initial={"show"}
          animate={sections.sec1 ? "show" : "exit"}
          transition={screenSpringTransition}
          variants={anim_x0y1}
          className="absolute inset-0 z-40"
        >
          <Section1 sections={sections} setSections={setSections} />
        </motion.div>

        {sections.sec2exit ? (
          <motion.div
            initial={"show"}
            animate={sections.sec2exit ? "exit" : "show"}
            transition={screenSpringTransition}
            variants={anim_x1y0}
            className="absolute inset-0 overflow-hidden z-40"
          >
            <Section2 sections={sections} setSections={setSections} />
          </motion.div>
        ) : (
          <motion.div
            initial={"hidden"}
            animate={sections.sec2 ? "show" : "hidden"}
            transition={screenSpringTransition}
            variants={anim_x0y1}
            className="absolute inset-0 overflow-hidden z-40"
          >
            <Section2 sections={sections} setSections={setSections} />
          </motion.div>
        )}

        {sections.sec3 && (
          <motion.div
            className={"absolute inset-0 overflow-hidden h-screen z-30"}
          >
            <Section3 sections={sections} setSections={setSections} />
          </motion.div>
        )}

        {sections.sec4 && (
          <motion.div
            initial={"hidden"}
            animate={sections.sec4 ? "show" : "hidden"}
            transition={screenSpringTransition}
            variants={anim_x}
            className="absolute inset-0 overflow-hidden h-screen z-40"
          >
            <Section4 sections={sections} setSections={setSections} />
          </motion.div>
        )}

        {sections.sec4exit && (
          <motion.div
            initial={"show"}
            animate={sections.sec4exit ? "exit" : "show"}
            transition={screenSpringTransition}
            variants={anim_x}
            className="absolute inset-0 overflow-hidden h-screen z-20"
          >
            <Section4 sections={sections} setSections={setSections} />
          </motion.div>
        )}
      </main>

      <footer>
        {sections.sec5 && (
          <motion.div
            initial={"show"}
            animate={"show"}
            transition={screenSpringTransition}
            variants={anim_y}
            className="absolute inset-0 overflow-hidden h-screen z-40"
          >
            <Section5 sections={sections} setSections={setSections} />
          </motion.div>
        )}
      </footer>
    </>
  );
};

export default Home;
